name: Release binaries for Windows

# DISABLED: needs review and fixes before re-enabling auto triggers
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Binstall
        uses: cargo-bins/cargo-binstall@main

      - name: install Tauri
        run: cargo binstall tauri-cli --no-confirm

      - name: npm install (desktop)
        working-directory: desktop
        run: npm install

      - name: npm install (librtbit/webui)
        working-directory: crates/librtbit/webui
        run: npm install

      - name: cargo tauri build
        working-directory: desktop
        run: cargo tauri build --ci

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/release/bundle/msi/rtbit-desktop_*_x64_en-US.msi

      - name: Build release
        run: cargo build --profile release-github

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            target/release-github/rtbit.exe
